use_frameworks!

target 'Less_Example' do
  pod 'Less', :path => '../'
  pod 'SDWebImage'
  pod 'MBProgressHUD'

  target 'Less_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
